# Generated by Django 5.1.3 on 2025-03-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanbanboard', '0004_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
